[package]
name = "print3rs-gui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.0", features = ["tokio"] }
print3rs-core = { path = "../print3rs-core" }
gcode-serializer = { path = "../gcode-serializer" }
tokio-serial = { version = "5.4.4", features = ["libudev"] }
